common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: matt22
  socket: /tmp/mysql.sock

development:
  <<: *common
  database: food-chain_dev

test:
  <<: *common
  database: food-chain_test

production:
  <<: *common
  database: food-chain_prod
